basePath: /
definitions:
  github_com_DioSaputra28_belejar-go-dasar_internal_category_model.Category:
    properties:
      description:
        description: Category description
        example: Makanan sehari-hari
        type: string
      id:
        description: Category ID
        example: 1
        type: integer
      name:
        description: Category name
        example: Makanan
        type: string
    type: object
  github_com_DioSaputra28_belejar-go-dasar_internal_produk_model.Produk:
    properties:
      harga:
        description: Product price
        example: 3500
        type: integer
      id:
        description: Product ID
        example: 1
        type: integer
      nama:
        description: Product name
        example: Indomie Godog
        type: string
      stok:
        description: Product stock
        example: 10
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: dio@example.com
    name: API Support
  description: This is a simple REST API for managing products and categories
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Product & Category API
  version: "1.0"
paths:
  /api/category:
    get:
      description: Get list of all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_category_model.Category'
            type: array
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category with the input payload
      parameters:
      - description: Category to create
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_category_model.Category'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_category_model.Category'
        "400":
          description: Invalid request
          schema:
            type: string
      summary: Create a new category
      tags:
      - categories
  /api/category/{id}:
    delete:
      description: Delete a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid Category ID
          schema:
            type: string
        "404":
          description: Category not found
          schema:
            type: string
      summary: Delete category
      tags:
      - categories
    get:
      description: Get a single category by its ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_category_model.Category'
        "400":
          description: Invalid Category ID
          schema:
            type: string
        "404":
          description: Category not found
          schema:
            type: string
      summary: Get category by ID
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update an existing category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category to update
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_category_model.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_category_model.Category'
        "400":
          description: Invalid request
          schema:
            type: string
        "404":
          description: Category not found
          schema:
            type: string
      summary: Update category
      tags:
      - categories
  /api/produk:
    get:
      description: Get list of all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_produk_model.Produk'
            type: array
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product with the input payload
      parameters:
      - description: Product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_produk_model.Produk'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_produk_model.Produk'
        "400":
          description: Invalid request
          schema:
            type: string
      summary: Create a new product
      tags:
      - products
  /api/produk/{id}:
    delete:
      description: Delete a product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid Produk ID
          schema:
            type: string
        "404":
          description: Produk belum ada
          schema:
            type: string
      summary: Delete product
      tags:
      - products
    get:
      description: Get a single product by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_produk_model.Produk'
        "400":
          description: Invalid Produk ID
          schema:
            type: string
        "404":
          description: Produk belum ada
          schema:
            type: string
      summary: Get product by ID
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update an existing product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_produk_model.Produk'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_DioSaputra28_belejar-go-dasar_internal_produk_model.Produk'
        "400":
          description: Invalid request
          schema:
            type: string
        "404":
          description: Produk belum ada
          schema:
            type: string
      summary: Update product
      tags:
      - products
swagger: "2.0"
